// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The policy used to specify data masking rule.
public struct DataMaskingPolicy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// A masking expression to bind to the data masking rule.
  public var maskingExpression: OneOf_MaskingExpression? = nil

  /// Initialize a new instance of `DataMaskingPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataMaskingPolicy().with { $0.predefinedExpression = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case predefinedExpression = "predefinedExpression"
    case routine = "routine"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var maskingExpression: OneOf_MaskingExpression? = nil
    let maskingExpressionCheckAndSet = {
      if maskingExpression != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'maskingExpression'"))
      }
      maskingExpression = $0
    }
    if let predefinedExpression = try container.decodeIfPresent(
      DataMaskingPolicy.PredefinedExpression.self, forKey: .predefinedExpression)
    {
      try maskingExpressionCheckAndSet(.predefinedExpression(predefinedExpression))
    }
    if let routine = try container.decodeIfPresent(Swift.String.self, forKey: .routine) {
      try maskingExpressionCheckAndSet(.routine(routine))
    }
    self.maskingExpression = maskingExpression
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.maskingExpression {
      switch choice {
      case .predefinedExpression(let value):
        try container.encode(value, forKey: .predefinedExpression)
      case .routine(let value):
        try container.encode(value, forKey: .routine)
      }
    }
  }

  /// The available masking rules. Learn more here:
  /// https://cloud.google.com/bigquery/docs/column-data-masking-intro#masking_options.
  public enum PredefinedExpression: Codable, Equatable, Sendable {
    /// Default, unspecified predefined expression. No masking will take place
    /// since no expression is specified.
    case unspecified
    /// Masking expression to replace data with SHA-256 hash.
    case sha256
    /// Masking expression to replace data with NULLs.
    case alwaysNull
    /// Masking expression to replace data with their default masking values.
    /// The default masking values for each type listed as below:
    ///
    /// * STRING: ""
    /// * BYTES: b''
    /// * INTEGER: 0
    /// * FLOAT: 0.0
    /// * NUMERIC: 0
    /// * BOOLEAN: FALSE
    /// * TIMESTAMP: 1970-01-01 00:00:00 UTC
    /// * DATE: 1970-01-01
    /// * TIME: 00:00:00
    /// * DATETIME: 1970-01-01T00:00:00
    /// * GEOGRAPHY: POINT(0 0)
    /// * BIGNUMERIC: 0
    /// * ARRAY: []
    /// * STRUCT: NOT_APPLICABLE
    /// * JSON: NULL
    case defaultMaskingValue
    /// Masking expression shows the last four characters of text.
    /// The masking behavior is as follows:
    ///
    /// * If text length > 4 characters: Replace text with XXXXX, append last
    /// four characters of original text.
    /// * If text length <= 4 characters: Apply SHA-256 hash.
    case lastFourCharacters
    /// Masking expression shows the first four characters of text.
    /// The masking behavior is as follows:
    ///
    /// * If text length > 4 characters: Replace text with XXXXX, prepend first
    /// four characters of original text.
    /// * If text length <= 4 characters: Apply SHA-256 hash.
    case firstFourCharacters
    /// Masking expression for email addresses.
    /// The masking behavior is as follows:
    ///
    /// * Syntax-valid email address: Replace username with XXXXX. For example,
    /// cloudysanfrancisco@gmail.com becomes XXXXX@gmail.com.
    /// * Syntax-invalid email address: Apply SHA-256 hash.
    ///
    /// For more information, see [Email
    /// mask](https://cloud.google.com/bigquery/docs/column-data-masking-intro#masking_options).
    case emailMask
    /// Masking expression to only show the <i>year</i> of `Date`,
    /// `DateTime` and `TimeStamp`. For example, with the
    /// year 2076:
    ///
    /// * DATE         :  2076-01-01
    /// * DATETIME     :  2076-01-01T00:00:00
    /// * TIMESTAMP    :  2076-01-01 00:00:00 UTC
    ///
    /// Truncation occurs according to the UTC time zone. To change this, adjust
    /// the default time zone using the `time_zone` system variable.
    /// For more information, see [System variables
    /// reference](https://cloud.google.com/bigquery/docs/reference/system-variables).
    case dateYearMask
    /// Masking expression that uses hashing to mask column data.
    /// It differs from SHA256 in that a unique random value is generated for
    /// each query and is added to the hash input, resulting in the hash / masked
    /// result to be different for each query. Hence the name "random hash".
    case randomHash
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .sha256: return 1
      case .alwaysNull: return 2
      case .defaultMaskingValue: return 3
      case .lastFourCharacters: return 4
      case .firstFourCharacters: return 5
      case .emailMask: return 6
      case .dateYearMask: return 7
      case .randomHash: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PREDEFINED_EXPRESSION_UNSPECIFIED"
      case .sha256: return "SHA256"
      case .alwaysNull: return "ALWAYS_NULL"
      case .defaultMaskingValue: return "DEFAULT_MASKING_VALUE"
      case .lastFourCharacters: return "LAST_FOUR_CHARACTERS"
      case .firstFourCharacters: return "FIRST_FOUR_CHARACTERS"
      case .emailMask: return "EMAIL_MASK"
      case .dateYearMask: return "DATE_YEAR_MASK"
      case .randomHash: return "RANDOM_HASH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PredefinedExpression/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PREDEFINED_EXPRESSION_UNSPECIFIED": self = .unspecified
      case "SHA256": self = .sha256
      case "ALWAYS_NULL": self = .alwaysNull
      case "DEFAULT_MASKING_VALUE": self = .defaultMaskingValue
      case "LAST_FOUR_CHARACTERS": self = .lastFourCharacters
      case "FIRST_FOUR_CHARACTERS": self = .firstFourCharacters
      case "EMAIL_MASK": self = .emailMask
      case "DATE_YEAR_MASK": self = .dateYearMask
      case "RANDOM_HASH": self = .randomHash
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PredefinedExpression/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .sha256
      case 2: self = .alwaysNull
      case 3: self = .defaultMaskingValue
      case 4: self = .lastFourCharacters
      case 5: self = .firstFourCharacters
      case 6: self = .emailMask
      case 7: self = .dateYearMask
      case 8: self = .randomHash
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .sha256: return try container.encode(1)
      case .alwaysNull: return try container.encode(2)
      case .defaultMaskingValue: return try container.encode(3)
      case .lastFourCharacters: return try container.encode(4)
      case .firstFourCharacters: return try container.encode(5)
      case .emailMask: return try container.encode(6)
      case .dateYearMask: return try container.encode(7)
      case .randomHash: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// A masking expression to bind to the data masking rule.
  public enum OneOf_MaskingExpression: Codable, Equatable, Sendable {
    /// Optional. A predefined masking expression.
    case predefinedExpression(DataMaskingPolicy.PredefinedExpression)
    /// Optional. The name of the BigQuery routine that contains the custom
    /// masking routine, in the format of
    /// `projects/{project_number}/datasets/{dataset_id}/routines/{routine_id}`.
    case routine(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.datapolicies.v2.DataMaskingPolicy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
