// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleCloudGax

extension Clients {
  protocol DataPolicyServiceStub {
    func createDataPolicy(
      request: CreateDataPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataPoliciesV2.DataPolicy

    func addGrantees(
      request: AddGranteesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataPoliciesV2.DataPolicy

    func removeGrantees(
      request: RemoveGranteesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataPoliciesV2.DataPolicy

    func updateDataPolicy(
      request: UpdateDataPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataPoliciesV2.DataPolicy

    func deleteDataPolicy(
      request: DeleteDataPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getDataPolicy(
      request: GetDataPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataPoliciesV2.DataPolicy

    func listDataPolicies(
      request: ListDataPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataPoliciesV2.ListDataPoliciesResponse

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse
  }
}
