// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for the ListDataPolicies method.
public struct ListDataPoliciesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Resource name of the project for which to list data policies.
  /// Format is `projects/{project_number}/locations/{location_id}`.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of data policies to return. Must be a value
  /// between 1 and 1000. If not set, defaults to 50.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The `nextPageToken` value returned from a previous list request,
  /// if any. If not set, defaults to an empty string.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Filters the data policies by policy tags that they
  /// are associated with. Currently filter only supports
  /// "policy_tag" based filtering and OR based predicates. Sample
  /// filter can be "policy_tag:
  /// projects/1/locations/us/taxonomies/2/policyTags/3".
  /// You may also use wildcard such as "policy_tag:
  /// projects/1/locations/us/taxonomies/2*". Please note that OR predicates
  /// cannot be used with wildcard filters.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListDataPoliciesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListDataPoliciesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.datapolicies.v2.ListDataPoliciesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
